### ISSUE TITLE
Indiquer clairement où recevoir les retours sur le site

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#12]
Les courageux vont aller sur les dépôts `sill-api` et/ou `sill-web` mais il n'est pas clairement indiqué où faire des retours pour les évolutions du site.  Résultat, les gens font des retours par les réseaux sociaux, par email, etc. Il faut un seul endroit public qui permet à tout le monde de suivre les échanges.

**Comment by garronej** [comment]
J'ai ajouter un lien dans le footer: 
<img width="1083" alt="image" src="https://github.com/codegouvfr/sill-web/assets/6702424/85c39a30-5f93-47e0-a16a-1fdcf132b86e">

**Comment by bzg** [comment]
C'est très bien, merci !
