### ISSUE TITLE
Indiquer plus clairement que la création de compte concerne seulement les agents publics

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#16]
Dans les titres de https://sill.code.gouv.fr/add-software ?

> Mettre directement en avant que c'est une plateforme pour les agents et enrichie PAR les agents.

**Comment by garronej** [comment]
WDYT?  

<img width="953" alt="image" src="https://github.com/codegouvfr/sill-web/assets/6702424/780ca358-88be-4240-8c28-fab19503dfed">

**Comment by bzg** [comment]
C'est très bien, go.
