### ISSUE TITLE
Impssible de rajouter une instance

### ISSUE THREAD

**Issue by ptitloup** [codegouvfr/sill-web#18]
Bonjour, sur la page https://sill.code.gouv.fr/add-instance, je reseigne tous les champs mais quand je clique sur suivant, rien ne se passe. Aucun message d'erreur !
Merci pour votre aide

**Comment by bzg** [comment]
@garronej tu peux regarder ?

**Comment by garronej** [comment]
Je viens de coriger, merci @ptitloup pour avoir fait remonter le problème.  

J'ai aussi ajouter un boutton permettant d'ajouter une nouvelle instance directement depuis la fiche logiciel:  

![image](https://github.com/codegouvfr/sill-web/assets/6702424/6001ac78-ab13-4321-9838-88beb3e77736)

**Comment by bzg** [comment]
Merci !

**Comment by garronej** [comment]
Non c'est moi, j'aurais dû m'en appersevoir bien avant.

**Comment by ptitloup** [comment]
Merci à vous pour la prise en compte et la correction. A bientôt

**Comment by ptitloup** [comment]
super, ca fonctionne bien maintenant : https://sill.code.gouv.fr/detail?name=Esup-Pod&tab=instances
Par contre, il va me falloir un petit peu de temps pour rajouter toutes les instances : https://pod.esup-portail.org/liste-des-instances ...
