### ISSUE TITLE
Décalage entre nombre de logiciels (statistiques / nombre affiché)

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#19]
La page d'accueil actuelle indique 400 logiciels, mais il y en a seulement 379.

Peut-être que les 400 comptent aussi les logiciels libres qui ont été retirés du SILL ?

**Comment by garronej** [comment]
Ah oui!  
Bien vu!  
Je corrige le filtre!

**Comment by garronej** [comment]
Done!
