### ISSUE TITLE
Ajouter ou modifier ?

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#20]
Pour mettre à jour un logiciel, la formulation indique "Quel logiciel voulez-vous ajouter ?" au lieu de "Quel logiciel voulez-vous modifier ?"

![Screenshot 2023-07-03 at 13-13-37 Socle Interministériel des Logiciels Libres](https://github.com/codegouvfr/sill-web/assets/63500/cbe6be0c-a2c5-4da4-a564-769783d5f143)

**Comment by garronej** [comment]
Pardon,  
Le code avais été mis a jour ce matin mais je n'etais pas passer en prod:  

<img width="591" alt="image" src="https://github.com/codegouvfr/sill-web/assets/6702424/dbb0f932-2c51-4ce3-93ae-3ed107e68db1">
