### ISSUE TITLE
Lien mort

### ISSUE THREAD

**Issue by mathiaslacroix** [codegouvfr/sill-web#21]
Bonjour. Sur cette [page](https://sill.code.gouv.fr/detail?name=Matomo), le lien "En savoir plus" de la bulle d'info mène vers une page [404](https://code.gouv.fr/utiliser/marches-interministeriels-support-expertise-logiciels-libres/)
![Presse-papiers-10000](https://github.com/codegouvfr/sill-web/assets/46921066/e2ca3b42-981c-4046-87a8-f2f1f31b510a)

**Comment by garronej** [comment]
Bonjour, merci d'avoir fait remonter, je m'en occupe!
