### ISSUE TITLE
[SILL] Comment ajouter des extensions ?

### ISSUE THREAD

**Issue by bersyl91** [codegouvfr/sill-web#29]
La suite bureautique LibreOffice est déjà dans le SILL, mais la liste des extensions autorisées est limitée.
Par ailleurs, une extension n'est pas un logiciel indépendant qui justifierait une entrée distincte dans le SILL.
Comment donc faire entrer une extension (en l'occurrence : ReadText destinée à faire fonctionner le narrateur Windows avec LibreOffice) ?
Merci à tous

**Comment by garronej** [comment]
Bonjour @bersyl91,  

Vous pouvez référencer une extention en tant que "brique technique". Vous pouvez aussi associer le logicel a Libre office par le biais de mot clef.  

Nous avons dans la base de donnée la notion de "logiciel parent" mais ce n'es pas encore possible de renseigner via l'interface graphique.

**Comment by bzg** [comment]
Je ferme cette requête - pour l'instant on peut ajouter une extension comme on le fait pour un simple logiciel.
