### ISSUE TITLE
Permettre de créer une page de profil pour chaque utilisateur enregistré

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#32]

**Comment by garronej** [comment]
The server side work is completed.  
On to the frontend now.

**Comment by bzg** [comment]
Looking forward testing this!

**Comment by garronej** [comment]
1/3 there on the Frontend done.

**Comment by garronej** [comment]
@bzg Preview du mode édition:  

https://github.com/codegouvfr/sill-web/assets/6702424/a1da9183-ad66-45ba-bdea-56fa220b6e80

**Comment by garronej** [comment]
The User Profile page has been updated to allow for public visibility. Now, the software tools that an agent refers a user to are displayed prominently, along with a detailed use case description for each tool.

Example: [View Example Profile](https://sill-preprod.lab.sspcloud.fr/user?email=joseph.garrone%40code.gouv.fr)

Please note that these user profile-related features are currently only available in our pre-production environment: [Pre-Prod Environment](https://sill-preprod.lab.sspcloud.fr/).

@bzg and @hjonin. Please let me know when you both are ready and comfortable with moving this update to our production environment.

**Comment by hjonin** [comment]
I agree with Bastien's comment to improve readability.

> One idea: instead of suffixing each software with "référent technique" or "utilisateur", which produces a lot of redundant information, we could group software by categories and have a section called "Référent technique", then "Utilisateur"?

Also, for usability/utility, I wonder if a form wouldn't be a better design than a free text area. It would be easier to fill out and it would allow us to extract information easier.

**Comment by bzg** [comment]
Let's open another issue for improvements, if needed.
