### ISSUE TITLE
Réintégrer les données CNLL pour les prestataires

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#33]

**Comment by garronej** [comment]
Done (nothing had to be done ^^)

https://sill.code.gouv.fr/detail?name=NextCloud  

<img width="1023" alt="image" src="https://github.com/codegouvfr/sill-web/assets/6702424/56d50863-b86e-417f-95e5-3a374fe5fc2d">

**Comment by bzg** [comment]
Il faut revoir les formulations et l'ordre des liens.  Je propose:

``
- See service providers on the CNLL index
- See service providers on Comptoir du Libre
- Open Comptoir du Libre page
- Open Wikidata page
``

En résumé:

- Ne pas compter les providers pour le CNLL
- Mettre les deux liens de providers en haut
- Dire explicitement que le lien ADULLACT pointe vers le Comptoir du Libre
- Remplacer "sheet" par "page"

Est-ce OK pour toi ?

**Comment by garronej** [comment]
Je n'ai pas oublier que je doit faire ça...

**Comment by bzg** [comment]
> Je n'ai pas oublier que je doit faire ça...

Tu n'es plus en contrat avec la DINUM, donc tu ne "dois" rien.

(Ça va mieux en le disant.)

C'est comme tu veux et peux sur ton temps libre.

**Comment by bzg** [comment]
Je vois que c'est fait, je ferme.  @garronej si tu peux essayer d'aider à garder les issues sync avec le code, c'est cool !

**Comment by bzg** [comment]
Dépend de https://github.com/codegouvfr/sill-web/issues/55
