### ISSUE TITLE
Supprimer les liens vers https://etalab-2.gitbook.io/sill/

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#34]
Ne plus reposer sur gitbook.io pour la documentation.

**Comment by garronej** [comment]
Done

**Comment by bzg** [comment]
Merci !

**Comment by hjonin** [comment]
Est-ce qu'il s'agit aussi de rapatrier les `.md` dans ce repo ?

**Comment by bzg** [comment]
La doc est sur https://github.com/codegouvfr/sill-docs mais @hjonin c'est toi qui vois ce qui est préférable : en général, sauf s'il faut donner des accès en écriture distincts entre code et doc, je suis plutôt pour que la doc soit près du code.

**Comment by garronej** [comment]
A garder en tête que ici ce n'est que le code du front.  
Personnellement je préfère que la doc reste un depot a part pour que l'historique de commit reste plus lisible.

**Comment by bzg** [comment]
Ah oui, c'est vrai que s'il y a plusieurs dépôts c'est plus lisible de garder la doc dans un dépôt à part.

Pour la lisibilité des commits, on fera déjà un grand pas en se passant de gitbook et des commits sans sujet ;)

**Comment by garronej** [comment]
> Pour la lisibilité des commits, on fera déjà un grand pas en se passant de gitbook et des commits sans sujet ;)  

Non mais je veux dire, si on cherche ce qui à changer dans la dernière version 24 commit de doc ça fait beaucoup de bruits.  
Et après c'est pas la faute de GitBook si je ne met pas de sujet il y a un champ a remplire "describe your changes" que je ne remplis jamais... 🫣

**Comment by bzg** [comment]
Mh... on doit pouvoir lancer git en local pour grepper et trouver ce qu'on veut en ignorant la doc, ce "bruit" n'est pas très gênant.

Et pour l'absence de description dans les commits faits avec gitbook, c'est quand même un peu la faute à gitbook car l'interface WYSIWYG encourage le fait de "sauvegarder" plein de micro-changements pour lesquels on trouve inutile d'ajouter une description.

**Comment by garronej** [comment]
> Mh... on doit pouvoir lancer git en local pour grepper et trouver ce qu'on veut en ignorant la doc, ce "bruit" n'est pas très gênant.

Oui, du moment qu'on s'abstrein a un peut de dicipline avec les messages de commit (`doc: xxxx`)

> Et pour l'absence de description dans les commits faits avec gitbook, c'est quand même un peu la faute à gitbook car l'interface WYSIWYG encourage le fait de "sauvegarder" plein de micro-changements pour lesquels on trouve inutile d'ajouter une description.  

Je suis en partie d'accord avec toi étatant donnée que c'est comme ça que j'utilise GitBook mais je crois que c'est vraiment inérant au fait même d'avoir une interface WYSIWYG parce qu'ils nugent pour qu'on fasse des messages de commits.  

![image](https://github.com/codegouvfr/sill-web/assets/6702424/f0017f5c-6f84-4310-a8e0-35e4d51b9109)
