### ISSUE TITLE
thème keycloak: titre de la page

### ISSUE THREAD

**Issue by revolunet** [codegouvfr/sill-web#37]
Bonjour, je teste le thème keycloak... ce serait quoi la PR pour pouvoir modifier le titre du template keycloak ? 

<img width="762" alt="Capture d’écran 2023-07-28 à 23 21 14" src="https://github.com/codegouvfr/sill-web/assets/124937/07ff214c-90f7-45ab-9612-592d10e2d426">

Je vois que c'est codé en dur à ces deux endroits : 
 - https://github.com/codegouvfr/sill-web/blob/af51752ef0bbcf2dff4eeb2461d4d8aacc774acb/src/keycloak-theme/login/Template.tsx#L69
 - https://github.com/codegouvfr/sill-web/blob/af51752ef0bbcf2dff4eeb2461d4d8aacc774acb/src/keycloak-theme/account/Template.tsx#L104

**Comment by garronej** [comment]
Ouuuups.  

Désole pour ça!  

Qu'es que tu pense d'une variable d'environement a set sur le seveur Keycloak qui introduirais un peut de parametrisation runtime du theme?  

Si non il y a aussi le nom du realm qu'on peut lire facilement dans le kcContext  

![image](https://github.com/codegouvfr/sill-web/assets/6702424/17f86ea4-b061-46e1-ac3f-910098247b56)

**Comment by revolunet** [comment]
Le "display name" ou le "HTML display name" du realm, non ?

**Comment by garronej** [comment]
It's deploying!

**Comment by revolunet** [comment]
thanks sir 🙏

**Comment by revolunet** [comment]
Ca marche merci :)... comment changer le `appLocationOrigin` qui sert [à définir le lien](https://github.com/codegouvfr/sill-web/blob/main/src/keycloak-theme/login/valuesTransferredOverUrl.ts#L111C1-L111C1) ? 
J'ai l'impression que c'est un paramètre passé par l'application cliente ?

**Comment by garronej** [comment]
Je transmets l'information via l'url, mais il me semble peu pratique que demander aux utilisateurs d'ajouter un paramètre URL.

Ainsi, serait-il préférable d'établir une variable d'environnement au niveau du container Keycloak ? Je suis en train de préparer cette configuration. Fais-moi savoir si cela te convient.

Bien à toi,

**Comment by garronej** [comment]
Now you can seamlessly define the following environment variables on the Keycloak server, which will be appropriately integrated by the theme:  

```raw
DSFR_THEME_HOME_URL
DSFR_THEME_SERVICE_TITLE
DSFR_THEME_BRAND_TOP
```  

For more insights and details, consider referring to this specific commit: [GitHub commit](https://github.com/codegouvfr/sill-web/commit/01a58e06a007fa06499214f87d9d207981c3bbf7)

Here's an example of defining the environment variables during the deployment of Keycloak with Helm:  

<img width="399" alt="image" src="https://github.com/codegouvfr/sill-web/assets/6702424/db327dde-12e0-45de-a8aa-1411f33ae6ec">  

Isn't Keycloakify impressive?

**Comment by revolunet** [comment]
Thanks, nice `extraThemeProperties` indeed. as a not keycloak expert, maybe among the 12k realm settings theres a property for that 🤔

**Comment by revolunet** [comment]
I can confirm it works perfectly, thanks !

**Comment by garronej** [comment]
> maybe among the 12k realm settings theres a property for that 🤔  

I'm quite confident that there's no such setting that would be passed over to the FTL context. I've looked everywhere in the `kcContext`
