### ISSUE TITLE
keycloak: jar size

### ISSUE THREAD

**Issue by revolunet** [codegouvfr/sill-web#38]
Just some analysis notes on the keycloak theme size

The jar size is 67M and 265M uncompressed

- In this file, the resources folder is duplicated (login+account), and there are two dependencies that use 56M :

```
 14M    ./theme/dsfr/account/resources/resources_common/node_modules/rcue/dist/fonts
 14M    ./theme/dsfr/account/resources/resources_common/node_modules/patternfly/dist/fonts
 14M    ./theme/dsfr/login/resources/resources_common/node_modules/rcue/dist/fonts
 14M    ./theme/dsfr/login/resources/resources_common/node_modules/patternfly/dist/fonts
 ```
 
 - the `*.map` use 112 of 265 Mo

**Comment by garronej** [comment]
Thanks a lot for the investigation!  

Tons of pepole have been complaining about the JAR's size.  

I'll adress that, it's getting out of hands.  

I just inclue all resources from Keycloak but I'll do some cherry picking and we should reduce the size down to 2MB like temple os.

**Comment by garronej** [comment]
Hi @revolunet,  

I've extracted the theme in a standalone repo.  

https://github.com/codegouvfr/keycloak-theme-dsfr  

See you there :)
