### ISSUE TITLE
ASSETS

### ISSUE THREAD

**Issue by garronej** [codegouvfr/sill-web#4]

**Comment by bzg** [comment]
Un meilleur titre pour cette issue ?

**Comment by garronej** [comment]
Salut,  
J'ai oublier de la fermer, j'ai toujour une issue pour upload des assets dans ton mes projets. Example: https://github.com/garronej/evt/issues/1  
C'est juste une commodité

**Comment by bzg** [comment]
Ok, je n'avais pas vu que c'était une convention perso.
