### ISSUE TITLE
Traductions fr manquantes

### ISSUE THREAD

**Issue by qleroy** [codegouvfr/sill-web#41]
Pour la page `SoftwareForm.tsx`, il manque des traductions `"stepper title"` des Step2, Step3 et Step4.

Exemple à l'étape 4:

<img width="755" alt="Screenshot 2023-08-17 at 12 04 14" src="https://github.com/codegouvfr/sill-web/assets/9881262/ef06de7a-e036-4c2c-893d-5ef0d4bd0800">

C'est un oubli ou bien le travail est en cours ?

Je peux proposer des traductions.

**Comment by garronej** [comment]
Bonjour @qleroy,  
C'est un oublis! Merci d'avoir fait remonter!
Avec plaisir pour recevoir une PR!
