### ISSUE TITLE
Fix "A propos" page

### ISSUE THREAD

**Issue by hjonin** [codegouvfr/sill-web#43]
Link seems broken on https://sill.code.gouv.fr/readme.

**Comment by hjonin** [comment]
Fixed after moving https://github.com/codegouvfr/sill-docs/blob/d1c894242904d576eb964d93221a7f7aea8f5c2c/sill.md.

**Comment by hjonin** [comment]
Needs to update preprod env vars.

**Comment by garronej** [comment]
It's in codegouvfr/paris-sspcloud -> apps -> sill-preprod -> values.yaml

**Comment by hjonin** [comment]
Thanks!

**Comment by hjonin** [comment]
@garronej how can I deploy sill-api to preprod so that it takes this change into account?

**Comment by garronej** [comment]
Just bump the package.json's version number. If the CI passes you should see changes in preprod within 10min usually less.

You can see in the sill footer what version of sill-web and sill-api are running
