### ISSUE TITLE
Lire le README et les TOS directement dans le repo

### ISSUE THREAD

**Issue by hjonin** [codegouvfr/sill-web#44]
Actuellement, le README est lu depuis un repo externe (https://github.com/codegouvfr/sill-docs/blob/main/sill.md), servi via l'API et les TOS depuis leur url externe, servi également via l'API.
Serait-il possible de les inclure et de les lire directement depuis le repo (sans passer par l'API) ?

**Comment by bzg** [comment]
Il faut préserver la possibilité de mettre à jour `sill.md` et `tos_fr.md` sans avoir à redéployer l'application SILL.

Pour le _lieu_ de stockage des deux fichiers : je trouve que ce n'est pas absurde d'avoir `sill.md` dans [sill-docs](https://github.com/codegouvfr/sill-docs) et `tos_fr.md` dans [sill-web](https://github.com/codegouvfr/sill-web/), comme aujourd'hui.

Pour la _méthode_ d'appel des contenus, je ne sais pas si elles doivent ou non diverger, ça ne me paraît pas critique.

**Comment by garronej** [comment]
Je suis en passer par l'API car sur source hut il y a pas de cors donc on ne peut pas fetch directement depuis le browser.  
Si on passe par GitHub on doit pouvoir fetch directement depuis le front mais je pense qu'il vaut mieux laisser l'API gérer. Il faut de toute façon pouvoir configurer l'url en paramètre.

**Comment by hjonin** [comment]
> Il faut préserver la possibilité de mettre à jour sill.md et tos_fr.md sans avoir à redéployer l'application SILL.

Dans ce cas, cette tâche n'est plus pertinente et peut être directement fermée.
