### ISSUE TITLE
Quand on ajoute un logiciel via la saisie de l'entité Wikidata, ne pas contraindre en fonction de la licence

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#47]

**Comment by garronej** [comment]
Done!  

Now even non libre wikidate entries are listed.  

![image](https://github.com/codegouvfr/sill-web/assets/6702424/17eca0fe-8888-4e0f-8aa6-804c2fdd2e0f)

It's bette this way, it's easy, if a non libre software is added, to forcefully remove the coresponding commit in sill-data.  

Just a reminder: A new version will be published but it's not automatically deployed on code.gouv.fr. I can do it i you'd like.  

Best

**Comment by bzg** [comment]
Thank you!  No need to deploy, let's leave it to @hjonin when she has time to do it.
