### ISSUE TITLE
Typo sur la page de 7zip : «ect.» devrait être «etc.»

### ISSUE THREAD

**Issue by PaulCapron** [codegouvfr/sill-web#51]
Sur https://code.gouv.fr/sill/detail?name=7zip, il y a une faute de frappe à « e**tc**. ». Le T et le C sont inversés.

**Comment by garronej** [comment]
Merci d'avoir pris le temps de faire remonter!  

J'ai corrigé. La prochaine fois, n'hésitez pas à éditer directement vous-même la fiche.  
Si vous êtes agent public, vous pouvez vous créer un compte.

Cordialement,

**Comment by PaulCapron** [comment]
Monsieur Garonne,

> La prochaine fois, n'hésitez pas à éditer directement vous-même la fiche.

J’aurais bien préféré ! Mais n’étant pas agent public, ça m’est impossible :'-(

Bien à vous

**Comment by bzg** [comment]
Je me permets de fermer, merci !
