### ISSUE TITLE
Afficher les prestataires dans un onglet plutôt que dans "Liens utiles"

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#52]
L'onglet serait par exemple à droite de celui pour les logiciels similaires:

![2023-09-18-161106_1920x1200_scrot](https://github.com/codegouvfr/sill-web/assets/63500/084583b7-0ee9-430c-874f-e50fd70bc085)

**Comment by bzg** [comment]
Dépend de https://github.com/codegouvfr/sill-web/issues/55

**Comment by JeromeBu** [comment]
Ajouter l'onglet avant "Logiciel similaire", l'onglet contiendra une liste des logiciels similaires.

<img width="1229" alt="image" src="https://github.com/codegouvfr/sill-web/assets/22095555/485fdddf-f998-4b8e-bc9e-2d89ce9f7eea">

**Comment by JeromeBu** [comment]
@bzg on se dirige vers ça. ça te convient ? Je ne suis pas trop sur du wording. 

<img width="1098" alt="image" src="https://github.com/codegouvfr/sill-web/assets/22095555/e8f77874-8642-47c9-953b-faa5306da7f9">


--------------

Et autre chose j'ai l'impression que :
`website` et `cdl_url` sont toujours identique. Donc je n'affiche que l'un des deux s'ils sont identique. Mais s'ils sont systématiquement identique autant retirer `website`

**Comment by bzg** [comment]
Top !

- Mettre "comptoir" (sans "e")
- Améliorer la lisbilité entre le nom du prestataire et les liens (juste des espaces et/ou tirets ?)

**Comment by bzg** [comment]
> Et autre chose j'ai l'impression que website et cdl_url sont toujours identique. Donc je n'affiche que l'un des deux s'ils sont identique. Mais s'ils sont systématiquement identique autant retirer website

J'ai corrigé dans le jeu de données, c'était une erreur de mon côté.

**Comment by JeromeBu** [comment]
Cette issue a été traité. Je la ferme
