### ISSUE TITLE
Ajout mailto: pour joindre tous les référents d'un logiciel

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#56]
Afficher les mails des référents est utile, mais par défaut, un agent public qui n'en connaît aucun ne saura pas auquel s'adresser.

Il pourrait être utile d'avoir un lien mailto: proposant d'envoyer un mail à _tous_ les référents.

**Comment by JeromeBu** [comment]
<img width="1364" alt="image" src="https://github.com/codegouvfr/sill-web/assets/22095555/66ed5fba-6288-47e1-98c2-aaec658ddc7c">

Petite icone mail à mettre sous `nextcloud` (par exemple). Sur la ligne réferent (11), à droite

**Comment by JeromeBu** [comment]
<img width="903" alt="image" src="https://github.com/codegouvfr/sill-web/assets/22095555/0c8a2ed0-a634-4352-97c0-54eb9fd511c6">

C'est mergé avec cette nouvelle version. Je ferme l'issue
