### ISSUE TITLE
Disparition des liens vers le Comptoir du Libre, sur la page SILL d'un logiciel 

### ISSUE THREAD

**Issue by dzc34** [codegouvfr/sill-web#58]
## Résumé

Dans l'ancienne version du site web du SILL, pour chaque logiciel présent sur le _Comptoir du Libre_, il y avait :
- un lien vers la page _Comptoir_ du logiciel.
- un lien vers la page _Comptoir_ des prestataires du logiciel.

Actuellement, les liens vers le _Comptoir_ ne sont plus présents sur le site web du SILL.

## Échanges 

bug remonté par mail  :
> Les données du _Comptoir_ sont bien présentes dans les données JSON du SILL : https://code.gouv.fr/sill/api/sill.json
> 
> En revanche, les liens vers le _Comptoir_ ne sont plus présents, en particulier les liens vers les prestataires du _Comptoir_ à l'inverse des liens vers les "prestataires de l'annuaire _CNLL_". 
> 
> Exemple avec Nexcloud (prestataires présents sur les sites du _CNLL_ et du _Comptoir_) :
> -  https://code.gouv.fr/sill/detail?name=NextCloud
> -   https://comptoir-du-libre.org/fr/softwares/servicesProviders/117
> 
> Exemple avec Dokiel  (prestataires présents uniquement sur le site du _Comptoir_) :
> - https://code.gouv.fr/sill/detail?name=Dokiel
> - https://comptoir-du-libre.org/fr/softwares/467

réponse de @bzg :
> oui, je confirme qu'il y a un bug quelque part. Peux-tu ouvrir une issue ?
> (...)
> À noter que nous avons ce travail en cours : https://github.com/codegouvfr/sill-web/issues/55

ping @garronej

**Comment by garronej** [comment]
Hi @dzc34,  

Thanks for reporting.  
It's fixed.  

It was caused by: https://github.com/codegouvfr/sill-api/commit/638ec7c653589d0d92e5f5bdb2fc2d1ae9a33c23  
The corresponding change on the frontend wasn't deployed (the version number needs to be bumped on sill-web).

**Comment by bzg** [comment]
Thanks for the quick fix!
