### ISSUE TITLE
Lien site officiel nomacs dangereux !

### ISSUE THREAD

**Issue by ZeBen84** [codegouvfr/sill-web#62]
Bonjour,

Le lien pour le site officiel du logiciel nomacs redirige vers un site vendant des stéroides car le domaine a changé de propriétaire.

https://code.gouv.fr/sill/detail?name=nomacs

Voici le lien github officiel : https://github.com/nomacs/nomacs

Néanmoins, le logiciel n'est plus mis à jour depuis plus de trois ans maintenant, il faudrait peut être le retirer de la liste.

**Comment by garronej** [comment]
Merci du signalement!

**Comment by garronej** [comment]
Le problème est qu'il s'agit de leur site officiel. C'est classique avec le wordpress.  
Il y a une issue: https://github.com/nomacs/nomacs/issues/997
Je ne vais pas déréférencé le logiciel car il est toujours activement maintenu mais j'ai suprimer le lien a Wikidata pour que le site officiel ne soit plus présent.
