### ISSUE TITLE
Changer les Prérogatives pour une entrée dans le SILL

### ISSUE THREAD

**Issue by ptitloup** [codegouvfr/sill-web#63]
Bonjour,
Suite à une mise à jour de notre logiciel, nous aimerions changer les Prérogatives de sa fiche dans le SILL.
En effet, nous respectons maintenant le RGAA et j'aimerais le spécifier.
Pouvez-vous me dire comment ?
Je vous en remercie
Bonne journée

**Comment by ptitloup** [comment]
Bonjour Joseph, j'ai un compte, je susi referens de la solution mais pas possible de dire qu'elle est RGAA compliant (ou alors je suis passé à côté)
Merci

**Comment by ptitloup** [comment]
Idem pour la version mobile (on a rajouté des fonctionnalités pwa)

**Comment by garronej** [comment]
Ah oui en effet il manque une étape au forulaire :/

**Comment by garronej** [comment]
Pour l'app mobile, c'est a létape 1 

<img width="627" alt="image" src="https://github.com/codegouvfr/sill-web/assets/6702424/0c378ddd-dc0e-4497-aaba-e8a95f166922">

Pour le RGPD, c'est normalement a l'étape 3 mais j'ai oublier de rajouter l'input. Je vais le faire.

**Comment by garronej** [comment]
C'est fait.  

<img width="519" alt="image" src="https://github.com/codegouvfr/sill-web/assets/6702424/d8184cba-efad-484a-8295-7bcf257ee591">  

Par contre, je ne travaille plus a la DINUM. Je n'ai donc plus accès au serveur de prod. Le laisse @hjonin ou @bzg déployer la dernière version.

**Comment by bzg** [comment]
Vu, merci pour l'implémentation, je laisse @hjonin déployer selon son calendrier.

**Comment by ptitloup** [comment]
En fait, notre service est une plateforme web mais que l'on peut "installer" sur iphone et android.
De ce fait, le choix unique empeche ce type de logiciel

**Comment by ptitloup** [comment]
Merci pour les modifications et la prise en compte de ma demande.

**Comment by bzg** [comment]
> De ce fait, le choix unique empeche ce type de logiciel

Oui - peux-tu ouvrir une autre issue pour permettre le choix multiple ici ?

PS: Le risque est de ne pas pouvoir spécifier le niveau de respect du RGAA pour chacun des choix quand plusieurs sont pertinents... mais nous pouvons assumer que les différentes implémentations ont sensiblement le même niveau de conformité pour l'instant.

**Comment by ptitloup** [comment]
Fait ! Merci à vous

**Comment by bzg** [comment]
> Fait ! Merci à vous

Super, merci !
