### ISSUE TITLE
Modifier les instances référencées

### ISSUE THREAD

**Issue by ptitloup** [codegouvfr/sill-web#64]
Bonjour,
Pourriez-vous rajouter la possibilité de modifier une instance référencée ? (la supprimer, changer son nom ou son url)
Merci

**Comment by bzg** [comment]
Gardons publiques dans ces issues les discussions sur les propositions d'évolution, ça permettra à tout le monde de suivre.

+1 pour l'idée de pouvoir éditer les instances ajoutées, je pensais que c'était déjà le cas.

**Comment by JeromeBu** [comment]
On va avoir quelque chose qui ressemblera à ça :

<img width="1267" alt="image" src="https://github.com/codegouvfr/sill-web/assets/22095555/a3bd237b-2353-49b6-a955-d1b0457a4d2f">

Qui renverra vers le formulaire pour modifier l'instance

**Comment by ptitloup** [comment]
Merci !
