### ISSUE TITLE
"Dernière version" qui est en réalité la première

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#66]
Pour https://code.gouv.fr/sill/detail?name=IS%20Designer la dernière version indiquée ([OD4IS_On_OD7](https://github.com/ObeoNetwork/InformationSystem/releases/tag/OD4IS_On_OD7)) est en réalité l'une des premières.  Cela envoie un très mauvais signal.

**Comment by garronej** [comment]
Ah oui non ça en effet je vais corriger tout de suite!  
Merci de me l'avoir fait remarquer. Je fait une requette graphql pour avoir les dernièrs tags avec la date. Je ne comprend pas pourquoi un tag de 2015 sort ❓ ❓ .  

Je regarde ça?

**Comment by garronej** [comment]
C'est un peut plus dûr que ce que j'avais anticipé.  
Certain tags ne sont pas taggé avec la date c'est pour ça que sur certains logiciels il y a de mauvais résultat.  
Il faut faire une analyse sémentique des numéro de versions.  
Je vais le faire.

**Comment by garronej** [comment]
Voilà, c'est corrigé.  
Voir préprod:  
https://sill-preprod.lab.sspcloud.fr/detail?name=IS%20Designer  

Pour mettre a jour en prod il suffit d'executer `./sill-update.sh`  

Les nouvelles version prendrons une bonne heure a être visible, le temps que tout soit recalculer.

**Comment by bzg** [comment]
Top, merci beaucoup ! 🧢
