### ISSUE TITLE
Correction d'une faute de frappe

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#70]
![migrer](https://github.com/codegouvfr/sill-web/assets/63500/8bc2d759-306e-4729-a1c5-171571f3a579)

**Comment by garronej** [comment]
Salut @bzg,  

Je suis perplexe, il s'agit d'une capture d'écran d'un très vieux thème Keycloak, quand nous étions encore sur Onyxia-UI.  
Pourrais-tu m'expliquer comment tu es arrivé a voir ce message, normalement ce thème n'est plus déployé nulle part...

**Comment by bzg** [comment]
C'est une ancienne DM sur Twitter que j'ai retrouvée - s'il n'y a plus la faute d'orthographe, on peut fermer l'issue, pas de souci.
