### ISSUE TITLE
Eviter le surlignage bleu qui donne l'impression que ce sont des liens

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#73]
Sur la page d'accueil:

![Screenshot 2023-10-27 at 10-24-14 Socle Interministériel des Logiciels Libres](https://github.com/codegouvfr/sill-web/assets/63500/cd48db80-a197-45e3-9b16-f793a9e2943b)

**Comment by vinber** [comment]
je dirais plutôt faire des liens hypertexte :)

**Comment by bzg** [comment]
> je dirais plutôt faire des liens hypertexte :)

Oui, aussi !

**Comment by vinber** [comment]
pour préciser, quand je suis arrivé sur la page, effectivement, dans ce texte résumé, j'avais tous les mots clés m'intéressant pour ajouter un logiciel au SILL, en ayant préalablement vérifié les critères, licences, ... et donc effectivement l'envie de cliquer :)

**Comment by bzg** [comment]
- Socle interministériel de logiciels libres: mettre en noir
- catalogue de référence: mettre en noir
- administration française: mettre en noir
- logiciels libres: mettre un lien vers https://fr.wikipedia.org/wiki/Logiciel_libre
- article 16: mettre un lien vers https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000033203039
- critères d'entrée: mettre un lien vers https://code.gouv.fr/sill/readme
- licence libre adaptée: mettre un lien vers https://code.gouv.fr/fr/doc/licences-libres-dinum/
- référents SILL: mettre en noir
