### ISSUE TITLE
Ordre alphabétique pour les filtres

### ISSUE THREAD

**Issue by mfaurel** [codegouvfr/sill-web#74]
Bonjour,
Serait-il possible de trier les filtres par ordre alphabétique ?

De plus, il y a parfois une entité qui apparaît plusieurs fois comme "MD: Ministère de la Défense".

![image](https://github.com/codegouvfr/sill-web/assets/12185901/1f3d855c-1765-402c-91b7-6bb3e594678d)

**Comment by garronej** [comment]
Bonjour @mfaurel,

Merci d'avoir signalé le bug de duplication d'entrées. Je viens de le corriger.

En ce qui concerne le classement des entrées par ordre alphabétique, les organismes sont actuellement classés par le nombre de logiciels libres utilisés. Je trouve légitime que les organismes les plus investis dans l'utilisation de logiciels libres soient mis en avant, mais je laisse l'équipe en charge du projet se prononcer sur cet aspect.

**Comment by garronej** [comment]
PS : Pour l'équipe, le bug de la duplication était dû à une ancienne version du SILL qui enregistrait le nom complet de l'organisme alors que seul l'acronyme est attendu. J'ai corrigé dans la base de données les entrées utilisateurs ayant été générées par cette ancienne version, le problème ne devrait plus survenir.

**Comment by mfaurel** [comment]
Peut-on mettre dans l'ordre alphabétique les 'catégories' ?
L'ordre 'quantitatif' n'a pas d'intérêt pour ce filtre.

**Comment by bzg** [comment]
J'ai remonté cela pour la 1.4, merci pour la suggestion.
