### ISSUE TITLE
Pour la question RGAA : proposer les choix oui, non et non-applicable 

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#77]

**Comment by bzg** [comment]
Au moment de l'ajout d'un logiciel, on demande si le logiciel respecte le RGAA: il faut pouvoir dire `N/A` car la question n'est pas pertinente pour tous les logiciels.

**Comment by JeromeBu** [comment]
Ca se passe ici :

<img width="1264" alt="image" src="https://github.com/codegouvfr/sill-web/assets/22095555/719efcb3-5560-4151-afaf-da504eda4def">
