### ISSUE TITLE
Mettre en avant le lien vers la documentation du logiciel référencé

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-web#90]

**Comment by garronej** [comment]
Ce n'est pas le lien "official website"?  

<img width="1326" alt="image" src="https://github.com/codegouvfr/sill-web/assets/6702424/5189eb17-de16-48bd-833d-c57032b1cfd2">

**Comment by bzg** [comment]
Non, il y a le lien vers le site officiel ([wd](https://www.wikidata.org/wiki/Property:P856)) et le lien vers le « mode d'emploi » ([wd](https://www.wikidata.org/wiki/Property:P2078)).

Ton image donne envie de mettre ce lien (quand il est détecté sur Wikidata, ce n'est pas souvent renseigné) entre le site officiel et le dépôt de code source.

**Comment by JeromeBu** [comment]
On peut mettre le lien entre les deux boutons en haut à droite
