### ISSUE TITLE
Wrong assertion encountered

### ISSUE THREAD

**Issue by agrimal** [codegouvfr/sill-web#93]
Bonjour, lors de la tentative d'ajout d'un logiciel similaire, j'obtiens l'erreur suivante :

```json
{"error":{"json":{"message":"\"input\" needs to be an object when doing a batch call","code":-32600,"data":{"code":"BAD_REQUEST","httpStatus":400,"stack":"TRPCError: \"input\" needs to be an object when doing a batch call\n    at getInputs (/home/web/websites/sill/sill-api/node_modules/@trpc/server/dist/resolveHTTPResponse-94b380d2.js:107:23)\n    at Object.resolveHTTPResponse (/home/web/websites/sill/sill-api/node_modules/@trpc/server/dist/resolveHTTPResponse-94b380d2.js:121:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/web/websites/sill/sill-api/node_modules/@trpc/server/dist/nodeHTTPRequestHandler-11f3df04.js:63:24\n    at async /home/web/websites/sill/sill-api/node_modules/@trpc/server/dist/adapters/express.js:16:9"}}}}
```

**Comment by garronej** [comment]
Je regarde, merci pour re rapport.

**Comment by garronej** [comment]
@agrimal, pouvez vous me dire quelle logiciel vous essayez d'ajouter?

**Comment by agrimal** [comment]
J'essaye d'éditer la fiche OpenSVC pour y ajouter des logiciels similaires.

**Comment by garronej** [comment]
Quelle logiciel en particuler s'il vous plais?  

J'essaie de reproduire l'erreur.

**Comment by agrimal** [comment]
J'essaye d'ajouter Kubernetes, Corosync et Pacemaker en logiciels similaires.

**Comment by garronej** [comment]
@agrimal Problème corrigé, merci de l'avoir signalé!  

https://code.gouv.fr/sill/detail?name=OpenSVC

**Comment by garronej** [comment]
Par contre, je m'inquiète un peu du système de versionnement adopté par OpenSVC.

La version 2.1 du logiciel a été publiée en mars 2020 : https://github.com/opensvc/opensvc/releases/tag/2.1

Cependant, de nombreuses mises à jour ont été publiées entre-temps sous le même numéro de version, en écrasant la distribution : https://repo.opensvc.com/deb/

Qu'en penses-tu, @bzg ?

**Comment by bzg** [comment]
Le SILL n'est pas le bon endroit pour pousser des bonnes pratiques de développement des projets, donc nous ne pouvons pas sanctionner un logiciel même si les développeurs ont un usage bizarre du versionnement.

On doit juste récupérer le tag le plus récent.

Le champ "Version minimale recommandée" est manuelle et peut être édité par les référents si le champ "Dernière version" (tag) n'apporte pas la bonne information.

**Comment by garronej** [comment]
@bzg 

> On doit juste récupérer le tag le plus récent.  

C'est le cas, https://github.com/opensvc/opensvc/releases/tag/2.1 est le tag le plus recent.  

> Le SILL n'est pas le bon endroit pour pousser des bonnes pratiques de développement des projets, donc nous ne pouvons pas sanctionner un logiciel même si les développeurs ont un usage bizarre du versionnement.

Ok!
